### ISSUE TITLE
junit test logger - to be able to take testcase->classname as testsuite->name instead of assembly name as this helps in Integration with Qmetry for Automatic results import

### ISSUE THREAD

**Issue by ljanardhanan-qualitrol** [Siphonophora/mjconrad.com#12]

**Comment by ljanardhanan-qualitrol** [comment]
Created a new issue to initiate communication with the owner.

**Comment by Siphonophora** [comment]
Hi, please create this on https://github.com/spekt/junit.testlogger and we can discuss. Examples of what you want xml to look like would be helpful
